### PR TITLE
Mobile

### PR DESCRIPTION
**Pull request by Crashillo**
Adapt to mobile layout

**Pending**
- ~Punchcard~

❗️ ~Requires to remove `fullcontainer-xs` css classes in gobierto backoffice -> Edit templates~

### CODE REVIEW

**Comment by ferblape** [comment]
@Crashillo the layout you see in the Edit templates section is overwritten everyday by an automatic process that fetches the layout from gencat. We can't remove CSS classes that come from that layout, but we could add classes. Could this be implemented using a new class instead of removing one?

**Comment by Crashillo** [comment]
Punchcard now forces to scroll it on mobile devices. In order to achieve it, https://github.com/PopulateTools/gobierto/pull/2078 must be merged

**Comment by ferblape** [comment]
👍 ok to me!

**Comment by Crashillo** [comment]
Same history: https://github.com/PopulateTools/gobierto/pull/2080 must be merged

**Comment by ferblape** [comment]
This PR was never merged, we should go on and close it.

I miss some padding in the left and the top but I let you confirm it's ok:

screen shot 2019-01-17 at 08 34 08

**Comment by Crashillo** [comment]
No, it's not. These paddings you're talking about were fixed months ago. If I remember, that was related with the heading we brought from gencat. And it implied appending some extra class in the backoffice template.

**Comment by Crashillo** [comment]
Yupp, here it is https://github.com/PopulateTools/gobierto-gencat-engine/pull/15/commits/b1d172892262dc3b31d5b4fb4f19d9840bbcebe9
`no-fullcontainer-xs` must be appended to `container fullcontainer-xs theme-gencat` in the backoffice template

**Comment by ferblape** [comment]
Thanks I forgot to add that class to the ETL. Now looks better.

**Pull request merged**
