### PR TITLE
Replace momentjs

### PR DESCRIPTION
**Pull request by Crashillo**
## :v: What does this PR do?
`momentjs` has become a outdated library (maintainers recommend to use different libs), apart from its package size, so it better to replace the utilization with plain, buitl-in, no 3rd-party code

https://gencat.gobify.net/

### CODE REVIEW

**Comment by furilo** [comment]
Which are specific things that should be reviewed? Where is this used specifically?

**Comment by Crashillo** [comment]
Only in the datepicker, when you play with the date range

**Comment by furilo** [comment]
Its deployed? Have you tested all cases? I'm seeing this when you select "Todo"

**Comment by Crashillo** [comment]
No, it's not yet, the compilation is failing due to _fullcalendar_. I'm replacing that inner dependency to fetch it from a CDN, the old version we were using (3.x vs 6.x) of fullcalendar requires both `moment` and `jquery`

**Comment by Crashillo** [comment]
Now it's deployed

**Comment by Crashillo** [comment]
> https://github.com/PopulateTools/gobierto/pull/4267#issuecomment-2459726808
> If you select "Todo" there is a JS error.

Solved. It comes from the following code, it was trying to parse an empty date:

https://github.com/PopulateTools/gobierto-gencat-engine/blob/8b1f09b6fef972d57fc988d1a78f06f52ad4b7cb/app/views/gobierto_people/layouts/application.html.erb#L7

**Review by furilo — APPROVED** [review]

**Review by ferblape — APPROVED** [review]

**Pull request merged**
